# Source: gloo-mesh-agent/charts/rate-limiter/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: rate-limiter
    
  name: rate-limiter
  namespace: gloo-system
---
# Source: gloo-mesh-agent/charts/rate-limiter/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rate-limiter
  namespace: gloo-system
  labels:
    app: rate-limiter
    
rules:
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs/status
  verbs:
  - get
  - update
---
# Source: gloo-mesh-agent/charts/rate-limiter/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rate-limiter
  namespace: gloo-system
  labels:
    app: rate-limiter
    
subjects:
- kind: ServiceAccount
  name: rate-limiter
  namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: rate-limiter
  apiGroup: rbac.authorization.k8s.io
---
# Source: gloo-mesh-agent/charts/rate-limiter/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rate-limiter
    
  name: rate-limiter
  namespace: gloo-system
spec:
  selector:
    app: rate-limiter
    rate-limiter: rate-limiter
  type: ClusterIP
  ports:
  - name: grpc
    port: 8083
  - name: ready
    port: 8084
  - name: debug
    port: 9091
---
# Source: gloo-mesh-agent/charts/rate-limiter/templates/redis.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rate-limiter
    
  name: redis
  namespace: gloo-system
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
  selector:
    app: rate-limiter
    rate-limiter: redis
---
# Source: gloo-mesh-agent/charts/rate-limiter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rate-limiter
    
  name: rate-limiter
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: rate-limiter
      rate-limiter: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
        rate-limiter: rate-limiter
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
        
        proxy.istio.io/config: "{ \"holdApplicationUntilProxyStarts\": true }"
    spec:
      nodeSelector:
        solo-poc: "addons"
      tolerations:
        - key: cloud.google.com/solo-poc
          operator: Equal
          value: "addons"
          effect: NoSchedule
      serviceAccountName: rate-limiter
      containers:
      - image: "gcr.io/gloo-mesh/rate-limiter:0.7.6"
        imagePullPolicy: IfNotPresent
        name: rate-limiter
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: START_STATS_SERVER
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RL_PORT_GRPC
          value: "8083"
        - name: READY_PORT_HTTP
          value: "8084"
        - name: DEBUG_PORT
          value: "9091"
        - name: REDIS_URL
          value: redis:6379
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: READY_PATH_HTTP
          value: "/ready"
        - name: ALIVE_PATH_HTTP
          value: ""
        readinessProbe:
          httpGet:
            port: 8084
            path: /ready
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 750m
            memory: 1500Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
# Source: gloo-mesh-agent/charts/rate-limiter/templates/redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rate-limiter
    
  name: redis
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limiter
      rate-limiter: redis
  template:
    metadata:
      labels:
        app: rate-limiter
        rate-limiter: redis
    spec:
      nodeSelector:
        solo-poc: "addons"
      tolerations:
        - key: cloud.google.com/solo-poc
          operator: Equal
          value: "addons"
          effect: NoSchedule
      containers:
      - image: "docker.io/redis:6.2.6"
        imagePullPolicy:  IfNotPresent
        name: redis
        args:
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
      - name: data
        emptyDir: {}
---
