apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authconfigs.extauth.solo.io
spec:
  group: extauth.solo.io
  names:
    kind: AuthConfig
    listKind: AuthConfigList
    plural: authconfigs
    shortNames:
      - ac
    singular: authconfig
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# Source: gloo-mesh-agent/charts/ext-auth-service/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ext-auth-service
    
  name: ext-auth-service
  namespace: gloo-mesh-addons
---
# Source: gloo-mesh-agent/charts/ext-auth-service/templates/deployment.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ext-auth-service
    
  name: ext-auth-service-signing-key
  namespace: gloo-mesh-addons
type: Opaque
data:
  signing-key: "RWh6VzR1N00wOQ=="
---
# Source: gloo-mesh-agent/charts/ext-auth-service/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ext-auth-service
  namespace: gloo-mesh-addons
  labels:
    app: ext-auth-service
    
rules:
- apiGroups:
  - extauth.solo.io
  resources:
  - authconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extauth.solo.io
  resources:
  - authconfigs/status
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
---
# Source: gloo-mesh-agent/charts/ext-auth-service/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ext-auth-service
  namespace: gloo-mesh-addons
  labels:
    app: ext-auth-service
    
subjects:
- kind: ServiceAccount
  name: ext-auth-service
  namespace: gloo-mesh-addons
roleRef:
  kind: ClusterRole
  name: ext-auth-service
  apiGroup: rbac.authorization.k8s.io
---
# Source: gloo-mesh-agent/charts/ext-auth-service/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-auth-service
    
  name: ext-auth-service
  namespace: gloo-mesh-addons
spec:
  type: ClusterIP
  selector:
    app: ext-auth-service
  ports:
  - name: grpc
    port: 8083
  - name: debug
    port: 9091
  - name: health
    port: 8082
  - name: auth
    port: 9001
    protocol: TCP
---
# Source: gloo-mesh-agent/charts/ext-auth-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-auth-service
  name: ext-auth-service
  namespace: gloo-mesh-addons
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ext-auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      creationTimestamp: null
      labels:
        app: ext-auth-service
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: INFO
        - name: START_STATS_SERVER
          value: "true"
        - name: WATCH_NAMESPACE
        - name: SERVER_PORT
          value: "8083"
        - name: DEBUG_PORT
          value: "9091"
        - name: USER_ID_HEADER
        - name: PLUGIN_DIRECTORY
          value: /auth-plugins/
        - name: HEADERS_TO_REDACT
          value: authorization
        - name: HEALTH_FAIL_TIMEOUT
          value: "15"
        - name: HEALTH_HTTP_PORT
          value: "8082"
        - name: HEALTH_HTTP_PATH
          value: /healthcheck
        - name: HEALTH_LIVENESS_HTTP_PATH
          value: /livenesscheck
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: signing-key
              name: ext-auth-service-signing-key
        image: gcr.io/gloo-mesh/ext-auth-service:0.31.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenesscheck
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ext-auth-service
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 125m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: grpc-extauth
        image: quay.io/solo-io/passthrough-grpc-service-example
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9001
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ext-auth-service
      serviceAccountName: ext-auth-service
      terminationGracePeriodSeconds: 30
    
      